# ==========================
# Localhost API requests
# ==========================

# Create a new person
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Jon Doe",
  "number": "09-123123"
}

###

# Get all persons
GET http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

###

# Get person by MongoDB id
# Replace PERSON_ID with real id from GET /api/persons response
GET http://localhost:3001/api/persons/PERSON_ID HTTP/1.1
Content-Type: application/json

###

# Update person by MongoDB id
# Replace PERSON_ID with real id from GET /api/persons response
PUT http://localhost:3001/api/persons/PERSON_ID HTTP/1.1
Content-Type: application/json

{
  "name": "Jon Doe Updated",
  "number": "09-999999"
}

###

# Delete person by MongoDB id
# Replace PERSON_ID with real id from GET /api/persons response
DELETE http://localhost:3001/api/persons/PERSON_ID HTTP/1.1

###


# ==========================
# Render API requests
# ==========================

# Create a new person
POST https://render-test-bezw.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Jon Doe",
  "number": "09-123123"
}

###

# Get all persons
GET https://render-test-bezw.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

###

# Get person by MongoDB id
# Replace PERSON_ID with real id from GET /api/persons response
GET https://render-test-bezw.onrender.com/api/persons/PERSON_ID HTTP/1.1
Content-Type: application/json

###

# Update person by MongoDB id
# Replace PERSON_ID with real id from GET /api/persons response
PUT https://render-test-bezw.onrender.com/api/persons/PERSON_ID HTTP/1.1
Content-Type: application/json

{
  "name": "Jon Doe Updated",
  "number": "09-999999"
}

###

# Delete person by MongoDB id
# Replace PERSON_ID with real id from GET /api/persons response
DELETE https://render-test-bezw.onrender.com/api/persons/PERSON_ID HTTP/1.1