# ==========================
# Localhost API requests
# ==========================

# Create a new person
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Jon Doe",
  "number": "09-123123"
}

###

# Delete person with ID 1
DELETE http://localhost:3001/api/persons/1 HTTP/1.1
Content-Type: application/json

###

# Get all persons
GET http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

###

# Get person with ID 3
GET http://localhost:3001/api/persons/3 HTTP/1.1
Content-Type: application/json

###

# ==========================
# Render API requests
# ==========================

# Create a new person
POST http://render-test-bezw.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Jon Doe",
  "number": "424243"
}

###

# Delete person with ID 1
DELETE http://render-test-bezw.onrender.com/api/persons/1 HTTP/1.1
Content-Type: application/json

###

# Get all persons
GET http://render-test-bezw.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

###

# Get person with ID 3
GET http://render-test-bezw.onrender.com/api/persons/3 HTTP/1.1
Content-Type: application/json